name: Contact
version: 1.2.0
description: Contact plugin for Flextype.
icon: fas fa-envelope
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/Contact
bugs: https://github.com/flextype-plugins/Contact/issues
license: MIT

dependencies:
  flextype: 0.9.10
  phpmailer: '>=1.0.0'
