# enabled: true or false to disable the plugin
enabled: true

# Contact plugin priority
priority: 100

default_subject: Default subject
message_success: "Email sended."
from:
  name: Flextype
  email: sergey.romanenko@flextype.org
to:
  name: Flextype
  email: sergey.romanenko@flextype.org
